In [ ]:
import numpy as np
import pandas as pd

#Load the file students.csv and make sure Score Date is parsed as datetime
df = pd.read_csv('students.csv')
print(df.head())

   Student ID    Name  Age  Grade    Subject        City  Passed Score Date
0           1   Ahmed   25   88.0       Math       Cairo    True  1/15/2025
1           2    Sara   32   92.0    Physics  Alexandria    True  2/10/2025
2           3    Omar   19   65.0       Math        Giza   False  1/20/2025
3           4    Lina   28   78.0  Chemistry       Cairo    True   3/5/2025
4           5  Khaled   45   55.0    Physics    Mansoura   False  2/28/2025

In [ ]:
#Print the shape, columns list, and data types of the DataFrame.
df.shape

(9, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student ID  9 non-null      int64
 1   Name        9 non-null      object
 2   Age         9 non-null      int64
 3   Grade       8 non-null      float64
 4   Subject     9 non-null      object
 5   City        9 non-null      object
 6   Passed      9 non-null      bool
 7   Score Date  8 non-null      object
dtypes: bool(1), float64(1), int64(2), object(4)
memory usage: 645.0+ bytes

In [ ]:
df.dtypes

Student ID      int64
Name           object
Age             int64
Grade         float64
Subject        object
City           object
Passed           bool
Score Date     object
dtype: object

In [ ]:
#Show the first 7 rows and the last 3 rows.
df.head(7)

   Student ID    Name  Age  Grade    Subject        City  Passed Score Date
0           1   Ahmed   25   88.0       Math       Cairo    True  1/15/2025
1           2    Sara   32   92.0    Physics  Alexandria    True  2/10/2025
2           3    Omar   19   65.0       Math        Giza   False  1/20/2025
3           4    Lina   28   78.0  Chemistry       Cairo    True   3/5/2025
4           5  Khaled   45   55.0    Physics    Mansoura   False  2/28/2025
5           6    Nour   22    NaN    English  Alexandria    True  1/10/2025
6           7    Yara   30   89.0       Math       Cairo    True        NaN

In [ ]:
df.tail(3)

   Student ID     Name  Age  Grade    Subject   City  Passed Score Date
6           7     Yara   30   89.0       Math  Cairo    True        NaN
7           8  Mohamed   27   72.0  Chemistry   Giza    True  3/12/2025
8           8  Mohamed   27   72.0  Chemistry   Giza    True  3/12/2025

In [ ]:
#Show how many missing values in each column.
df.isna().sum()

Student ID    0
Name          0
Age           0
Grade         1
Subject       0
City          0
Passed        0
Score Date    1
dtype: int64

In [ ]:
#What is the average, minimum, and maximum Grade?
df['Grade'].max()

92.0

In [ ]:
df['Grade'].min()

55.0

In [ ]:
df['Grade'].mean()

np.float64(76.375)

In [ ]:
#•How many unique cities are there? List them.
df['City'].unique()

array(['Cairo', 'Alexandria', 'Giza', 'Mansoura'], dtype=object)

In [ ]:
#Use value_counts() to show how many students per Subject.
df['Subject'].value_counts()

Subject
Math         3
Chemistry    3
Physics      2
English      1
Name: count, dtype: int64

In [ ]:
#Select only the columns: Name, Grade, Subject, City.
df[['Name','Grade','Subject','City']]

      Name  Grade    Subject        City
0    Ahmed   88.0       Math       Cairo
1     Sara   92.0    Physics  Alexandria
2     Omar   65.0       Math        Giza
3     Lina   78.0  Chemistry       Cairo
4   Khaled   55.0    Physics    Mansoura
5     Nour    NaN    English  Alexandria
6     Yara   89.0       Math       Cairo
7  Mohamed   72.0  Chemistry        Giza
8  Mohamed   72.0  Chemistry        Giza

In [ ]:
#Show all students who Passed and have Grade ≥ 85.
df[(df['Passed'] == True) & (df['Grade'] >= 85)]

   Student ID   Name  Age  Grade  Subject        City  Passed Score Date
0           1  Ahmed   25   88.0     Math       Cairo    True  1/15/2025
1           2   Sara   32   92.0  Physics  Alexandria    True  2/10/2025
6           7   Yara   30   89.0     Math       Cairo    True        NaN

In [ ]:
#Show students whose Name contains the letter "a" or "A" (case insensitive)
df[df['Name'].str.contains('a', case=False)]

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True  1/15/2025
1           2     Sara   32   92.0    Physics  Alexandria    True  2/10/2025
2           3     Omar   19   65.0       Math        Giza   False  1/20/2025
3           4     Lina   28   78.0  Chemistry       Cairo    True   3/5/2025
4           5   Khaled   45   55.0    Physics    Mansoura   False  2/28/2025
6           7     Yara   30   89.0       Math       Cairo    True        NaN
7           8  Mohamed   27   72.0  Chemistry        Giza    True  3/12/2025
8           8  Mohamed   27   72.0  Chemistry        Giza    True  3/12/2025

In [ ]:
#Show students in Cairo or Alexandria with Grade < 80.
df[(df['City'].isin(['Cairo', 'Alexandria'])) | (df['Grade'] < 80)]

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True  1/15/2025
1           2     Sara   32   92.0    Physics  Alexandria    True  2/10/2025
2           3     Omar   19   65.0       Math        Giza   False  1/20/2025
3           4     Lina   28   78.0  Chemistry       Cairo    True   3/5/2025
4           5   Khaled   45   55.0    Physics    Mansoura   False  2/28/2025
5           6     Nour   22    NaN    English  Alexandria    True  1/10/2025
6           7     Yara   30   89.0       Math       Cairo    True        NaN
7           8  Mohamed   27   72.0  Chemistry        Giza    True  3/12/2025
8           8  Mohamed   27   72.0  Chemistry        Giza    True  3/12/2025

In [ ]:
#Show students with Grade between 80 and 90 (inclusive).
df[df['Grade'].between(80,90)]

   Student ID   Name  Age  Grade Subject   City  Passed Score Date
0           1  Ahmed   25   88.0    Math  Cairo    True  1/15/2025
6           7   Yara   30   89.0    Math  Cairo    True        NaN

In [ ]:
#Using .loc, change Khaled's grade from 55 to 68.
df.loc[df['Name'] == 'Khaled', ['Grade']] = 68

In [ ]:
df['Grade']

0    88.0
1    92.0
2    65.0
3    78.0
4    68.0
5     NaN
6    89.0
7    72.0
8    72.0
Name: Grade, dtype: float64

In [ ]:
#Add a new column Is_Excellent that is True if Grade ≥ 90, False otherwise (vectorized).
df['Is_Excellent'] = df['Grade'].map(lambda x:True if x >= 90 else False)

In [ ]:
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False
1,2,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True
2,3,Omar,19,65.0,Math,Giza,False,1/20/2025,False
3,4,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False
4,5,Khaled,45,68.0,Physics,Mansoura,False,2/28/2025,False
5,6,Nour,22,NaN,English,Alexandria,True,1/10/2025,False
6,7,Yara,30,89.0,Math,Cairo,True,NaN,False
7,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False
8,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False

In [ ]:
#Fill missing Grade values with the average Grade
df['Grade'].fillna(value=df['Grade'].mean(), inplace=True)

/tmp/ipykernel_607/182689400.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Grade'].fillna(value=df['Grade'].mean(), inplace=True)

In [ ]:
df['Score Date'].fillna(value=df['Score Date'].mode()[0], inplace=True)

/tmp/ipykernel_607/175247015.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Score Date'].fillna(value=df['Score Date'].mode()[0], inplace=True)

In [ ]:
#•Add a new column Final_Grade = Grade + 5 (bonus points).
df['Final_Grade'] = df['Grade'] + 5

In [ ]:
#Create a column Grade_Category using pd.cut with bins:
# •0–69 → "Fail"
# •70–79 → "Average"
# •80–89 → "Good"
# •90–100 → "Excellent"
bin = [0,70,80,90,100]
label = ["Fail", "Average", "Good", "Excellent"]
df['Grade_Category'] = pd.cut(df['Grade'], bins=bin , labels=label)

In [ ]:
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,1,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,93.0,Good
1,2,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,97.0,Excellent
2,3,Omar,19,65.0,Math,Giza,False,1/20/2025,False,70.0,Fail
3,4,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,83.0,Average
4,5,Khaled,45,68.0,Physics,Mansoura,False,2/28/2025,False,73.0,Fail
5,6,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,83.0,Average
6,7,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,94.0,Good
7,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average
8,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average

In [ ]:
# •Remove the column Student ID.
df.drop(columns=['Student ID'], inplace=True)

In [ ]:
# •Keep only students who Passed.
df = df[df['Passed'] == True]

In [ ]:
# •Sort the DataFrame by Grade descending.
df.sort_values(by='Grade', ascending=False)

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
1,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,97.0,Excellent
6,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,94.0,Good
0,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,93.0,Good
3,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,83.0,Average
5,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,83.0,Average
7,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average

In [ ]:
#•Sort by City ascending, then inside each city sort by Grade descending.
df.sort_values(by=['City','Grade'], ascending=[True,False])

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
1,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,97.0,Excellent
5,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,83.0,Average
6,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,94.0,Good
0,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,93.0,Good
3,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,83.0,Average
7,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average

In [ ]:
#•Add a column Rank that ranks students by Grade (1 = highest, handle ties with 'min').
df['Rank'] = df['Grade'].rank(ascending=True, method='dense')

/tmp/ipykernel_607/564111579.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Rank'] = df['Grade'].rank(ascending=False, method='dense')

In [ ]:
df

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
0,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,93.0,Good,3.0
1,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,97.0,Excellent,1.0
3,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,83.0,Average,4.0
5,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,83.0,Average,4.0
6,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,94.0,Good,2.0
7,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average,5.0
8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average,5.0

In [ ]:
#•Show the top 4 students with the highest grades (use nlargest).
df.nlargest(4,'Rank',keep='first')

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
1,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,97.0,Excellent,1.0
6,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,94.0,Good,2.0
0,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,93.0,Good,3.0
3,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,83.0,Average,4.0
5,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,83.0,Average,4.0

In [ ]:
# •Find the student(s) with the highest Grade and show their Name and Grade.
df[df['Grade'] == df['Grade'].max()][['Name', 'Grade']]

   Name  Grade
1  Sara   92.0

In [ ]:
#•After filling missing grades, recalculate the average Grade per Subject.
df.groupby('Subject')['Grade'].mean()

Subject
Chemistry    74.0
English      78.0
Math         88.5
Physics      92.0
Name: Grade, dtype: float64

In [ ]:
#•Create a new column City_Avg that shows the average grade of each student's city (using transform).
df['City_Avg'] = df.groupby('City')['Grade'].transform('mean')

/tmp/ipykernel_607/3641787075.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['City_Avg'] = df.groupby('City')['Grade'].transform('mean')

In [ ]:
#•Show the subject with the highest average grade.
df[df['Grade'] == df['Grade'].max()]['Subject']

1    Physics
Name: Subject, dtype: object

In [ ]:
df

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank,City_Avg
0,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,93.0,Good,3.0,85.0
1,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,97.0,Excellent,1.0,85.0
3,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,83.0,Average,4.0,85.0
5,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,83.0,Average,4.0,85.0
6,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,94.0,Good,2.0,85.0
7,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average,5.0,72.0
8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average,5.0,72.0